name             'flaskapp'
maintainer       'Bonobos, Inc.'
maintainer_email 'ehoffman@bonobos.com'
license          'All rights reserved'
description      'Installs/Configures flaskapp'
long_description 'Installs/Configures flaskapp'
version          '0.1.0'

depends           'application_python'
depends           'poise-python'
